---
title: Pitch Counts
---

Below are sortable tables showing the counts of pitches in each mode. This can be cross-references with the 
visualizations from the [pitch histogram page](pitch_histograms.qmd), or can be used for additional data analysis as needed.


## G Freygish

```{r, echo=F, warnings=FALSE, message=FALSE}
library(DT)
library(humdrumR)
library(tidyverse)
freygish <- readHumdrum('corpus/extracts/freygish/*.krn')
freygish |> 
    pitch(simple = FALSE) |>
    humdrumR::tally() |> 
    as_tibble() |> 
    arrange(desc(n)) 
```

## G "Raised Fourth"

```{r, echo=F, warnings=FALSE, message=FALSE}
raised <- readHumdrum('corpus/extracts/raised_four/*.krn')
raised |> 
    pitch(simple = FALSE) |>
    humdrumR::tally() |> 
    as_tibble() |> 
    arrange(desc(n)) 
```

## G Major

```{r, echo=F, warnings=FALSE, message=FALSE}

major <- readHumdrum('corpus/extracts/major/*.krn')
major <- major |> 
    pitch(simple = FALSE) 

major |> humdrumR::tally() |> as_tibble() |> 
    arrange(desc(n)) 
```

## G Minor

```{r, echo=F, warnings=FALSE, message=FALSE}
minor <- readHumdrum('corpus/extracts/minor/*.krn')
minor |> 
    pitch(simple = FALSE) |>
    humdrumR::tally() |> 
    as_tibble() |> 
    arrange(desc(n)) 
```
