---
title: Introduction
---

This website provides machine-readable music files, searchable metadata, mode analyses, and mode data for a corpus of klezmer tunes from the volume _Jewish Instrumental Folk Music_, compiled by the pre-eminent Ukrainian Jewish ethnomusicologist Moshe Beregovski (1892-1961). The volume was published posthumously, first in Russian (1987) and then in English (2001 and 2015). A hand-written manuscript of the volume is also available in Beregovski 2013. The tunes were collected from a variety of sources in Ukraine, in the decades before World War II, and the volume represents one of the most important sources for Jewish instrumental music from Eastern Europe, now known as klezmer (Slobin 1986, 253; Feldman 2016, 128).

The website is intended as a self-standing resource for musicians and scholars and as a supplement to an article by Malin and Shanahan, currently in progress. 

At present, this collection has 245 out of the 254 tunes in Beregovski’s volume, and sections from four additional tunes. It leaves out tunes and sections without a time signature or with variable meter (i.e., with varying time signatures and frequent fermatas). There are five pieces without a regular meter: the _Dobranoch_ no. 9, _Kale-bazetsns_ nos. 13 and 14, and the _Ava rabos_ nos. 17 and 18. There are also four pieces that begin without a regular meter and have metric sections at the end: the _Khtsos_ no. 19, the _Taksim_ no. 20, and the _Doinas_ nos. 21 and 22. The metric sections at the ends of these are included in the corpus.

The corpus was digitized from the second English edition by Research Assistants Rebecca Hamel and Izzy Fincher with funding from the Center for Humanities & the Arts and Program in Jewish Studies at the University of Colorado Boulder. Research Assistant Laine Gruver assisted with data entry for the website. 

This website enables searches based on Beregovski’s metadata, provides corpus-level data on mode, and a resource for further computational analysis. It is not a replacement for the full volume and does not include key features: editor’s notes by Slobin and Rothstein (from the first edition) and Bjorling (for the second), an introductory essay by Beregovski, remarks on the transcriptions by Beregovski, a music editor’s Note by Kurt Bjorling, an addendum by Izaly Zemtsovsky, and more. The music notation is also incomplete in some regards; see further notes below. The second edition is available from Kurt Bjorling at [https://muziker.org/](https://muziker.org/). The Russian edition is in the public domain and available from [https://yiddish-culture.com/ru/yiddish_ru/beregovsky-works_ru/](https://yiddish-culture.com/ru/yiddish_ru/beregovsky-works_ru/). 

There are two kinds of metadata on this site:

1. Metadata from Beregovski’s notes, which includes genre, source (i.e., the musician who performed, recorded, or notated the music), source type (recording, transcription, or manuscript), the source instrument or voice, the location where the item was collected, main region, subregion, the date it was collected, and the original location for instances where the musician reported learning the tune from somewhere else. 
2. Malin’s analysis of mode in the volume. This includes a modal designation for each tune as a whole, an indication of whether there are changes of mode, secondary modes (as applicable), the measures for secondary modes (as applicable), and additional notes for instances of ambiguity. 

This information is available in three searchable spreadsheets: (1) a complete spreadsheet with Beregovski’s metadata and Malin’s mode analysis, (2) a spreadsheet with Beregovki’s metadata on its own, and (3) a spreadsheet with Malin’s analysis on its own.

Beregovski notated all of the tunes in the volume in G for ease of comparison. Thus pitch data on this website correlates with scale-degree data. Passages that modulate to modes with other tonics are tagged and analyzed separately. 

Beregovski also notated the tunes with G<sub>4</sub> as the main tonic and our pitch data is differentiated by register. (It is based on pitch, not pitch-class.) Thus, G<sub>4 </sub>in the data represents the main tonic, D<sub>5</sub> represents scale-degree ^5 in the main 8ve and D<sub>4</sub> represents scale-degree ^5 in the octave below. 

The full methodology behind the mode analysis is provided in the article by Malin and Shanahan (in progress). We summarize four main criteria for the purposes of this website:

1. We identify mode by section, when possible; 
2. We document shifts at cadences when there is a return to a primary mode;
3. However, when two modes in a section share the same pitch collection and cadence in the primary mode (e.g., Bb major to G minor), we use the cadence as the guide;
4. We include modal shifts within a section when they are between secondary modes with no single mode taking obvious precedent.

Criteria no. 1 in particular means that if a section begins in one mode, departs briefly to another mode, and returns to the first mode, the digression is not included in the analysis. Further examples and explanations are provided in the article.

Malin’s analysis relies on a basic classification of four modes in klezmer music. The names given here are _freygish_, raised fourth, minor, and major. These same modes are sometimes known by other names, which reference Jewish prayer modes or the Church mode: _freygish_ = ahavah rabbah; raised fourth = altered Dorian or _misheberakh_; minor = _magen avot_; major = _adonai malakh_. Furthermore, while there are elements of Western European tonality, the “major” and “minor” modes in klezmer should not be taken as equivalent to major and minor keys in the European tradition. An introduction to the modes is provided in the article by Malin and Shanahan. Additional sources can be found in Beregovski 2015; Slobin 1980; Sokolow 1987; Horowitz 1993; Netsky 2015; Feldman 2016; and Rubin 2020. (See full citations in the references section.) 

Malin’s mode analysis answers three basic questions: What is the pitch profile of each mode? What are characteristic melodic tendencies of each mode? And what are characteristic modulation pathways? These questions can be explored with the data in this website; they are addressed directly in the article by Malin and Shanahan. The article and this website may also serve as the basis for comparison with adjacent repertoires from both Jewish and non-Jewish traditions. 

There are a few additional details that users of the corpus should take note of:

1. The corpus does not include local variants within tunes–i.e., places where Beregovski notated an additional option for a few measures. It also does not include the tune variants that come one right after the other in the volume. For instance, the corpus includes the Freylekhs no. 132, but not the variant 132a. The study of tune variants is an important topic in klezmer music, but it is not one that we deal with directly here. 
2. The digital music files at present do not include first and second endings. This is an issue that we expect to resolve soon. See the paper by Malin and Shanahan (in progress) for a discussion of how this affects the mode data.
3. Measure numbers in the mode analysis and digital music files are counted through the first and second endings in the music. For instance, if the first ending is measure 8, the second ending is counted here as measure 9. 


Here, readers can also find the corpus downloadable as kern files, as well as analyses conducted with the [Humdrum Toolkit](https://www.humdrum.org/guide/), and scores visualized with the [Verovio Humdrum Viewer](https://verovio.humdrum.org/). These analyses include frequency distributions, and *n-gram* analyses.

**References**

Beregovski, Moshe. 2001. _Jewish Instrumental Folk Music: The Collections and Writings of Moshe Beregovski_. Edited by Mark Slobin, Robert A. Rothstein, and Michael Alpert. Syracuse, N.Y: Syracuse University Press.

———. 2013. _Jewish Musical Folklore. 5 volumes, 5 CD Set._ Kiev: Dukh i Litera.

———. 2015. _Jewish Instrumental Folk Music: The Collections and Writings of Moshe Beregovski_. Edited by Mark Slobin, Michael Alpert, and Robert Rothstein. Second edition, Revised by Kurt Björling. Draft 3.4.

Beregovskiĭ, Moisei. 1987. _Еврейская народная инструментальная музыка (Evreiskaia narodnaia instrumental’naia muzyka)_. Edited by Goldin. Moscow: Советский композитор.

Feldman, Walter Zev. 2016. _Klezmer: Music, History, and Memory_. New York: Oxford University Press.

Horowitz, Joshua. 1993. “The Klezmer Freygish Shteyger: Mode, Sub-Mode and Modal Progression.” Unpublished manuscript.[ http://www.budowitz.com/Budowitz/Essays.html](http://www.budowitz.com/Budowitz/Essays.html).

Netsky, Hankus. 2015. _Klezmer: Music and Community in Twentieth-Century Jewish Philadelphia_. Philadelphia: Temple University Press.

Rubin, Joel E. 2020. _New York Klezmer in the Early Twentieth Century: The Music of Naftule Brandwein and Dave Tarras_. Rochester: University of Rochester Press.[ ](https://ebookcentral.proquest.com/lib/ucb/detail.action?docID=6272858)

Slobin, Mark. 1980. “The Evolution of a Musical Symbol in Yiddish Culure.” In _Studies in Jewish Folklore: Proceedings of a Regional Conference of the Association for Jewish Studies Held at the Spertus College of Judaica, Chicago_, 313–30. Cambridge, MA: Association for Jewish Studies. 

———. 1986. “A Fresh Look at Beregovski’s Folk Music Research.” _Ethnomusicology_ 30 (2): 253–60.

Sokolow, Pete. 1987. “A Few Notes and Observations on the Theory and Performance of Klezmer Music.” In _The Compleat Klezmer_, 19–28. Cedarhurst, N.Y.: Tara Publications.